account/urls.py
from django.urls import path

from .views import SignUpView, login_view, logout_view

app_name = 'account'

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view , name = 'logout'),
]

app/urls.py
from django.urls import path

from .views import HomePageView, question_list, result_list

app_name = 'app'

urlpatterns = [
    path('' , HomePageView.as_view() , name = 'home'),
    path('question/<slug:slug>' , question_list , name = 'question_list'),
    path('result/' , result_list , name = 'result_list'),
]

quiz/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin-secret/', admin.site.urls),
    path('account/' , include('account.urls')),
    path('' , include('app.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

account/models.py
from django.db import models


from django.contrib.auth.models import AbstractUser
from account.managers import UserManager



class CustomUser(AbstractUser):
    phone = models.CharField(max_length=13 , unique=True)
    username = None

    USERNAME_FIELD = 'phone'
    objects = UserManager()

    def __str__(self):
        return self.phone

app/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)

    def __str__(self):
        return self.name
    class Meta:
        verbose_name = "kategory"
        verbose_name_plural = "Kategoriyalar"
        ordering = ['name']



class Question(models.Model):
    name = models.CharField(max_length=255)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def is_correct_check(self, pk):
        return self.answers.filter(pk=pk, is_correct=True).exists()


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='answers')
    name = models.CharField(max_length=255)
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class Result(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    total_questions = models.IntegerField(default=0)
    total_correct = models.IntegerField(default=0)
    score = models.FloatField(default=0)

    def __str__(self):
        return self.user.phone

    def save(self, *args, **kwargs):
        self.score = (self.total_correct * 100) / self.total_questions
        return super().save(*args, **kwargs)

    @property
    def is_passed(self):
        return self.score >= 60

    @property
    def is_failed(self):
        return self.score < 60

account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model

User = get_user_model()


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("phone",)


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = User
        fields = ("phone", "first_name", "last_name")

class LoginForm(forms.Form):
    phone = forms.CharField(max_length=100)
    password = forms.CharField(max_length=100 , widget=forms.PasswordInput)


class SignUpForm(forms.ModelForm):
    password1 = forms.CharField(max_length=128, widget=forms.PasswordInput())
    password2 = forms.CharField(max_length=128, widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('phone', 'email', 'first_name', 'password1', 'password2')

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password1

    def save(self, commit=True):
        password1 = self.cleaned_data["password1"]
        user = super().save(commit=False)
        user.set_password(password1)
        if commit:
            user.save()
        return user

account/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import CreateView
from django.contrib.auth import get_user_model, logout, authenticate, login

from .forms import SignUpForm, LoginForm

User = get_user_model()


class SignUpView(CreateView):
    model = User
    form_class = SignUpForm
    template_name = 'accaount/signup.html'
    success_url = '/'

def login_view(request):
    form = LoginForm
    if request.method == 'POST':
        phone = request.POST['phone']
        password = request.POST['password']
        user = authenticate(request, phone=phone, password=password)
        if user is not None:
            login(request, user)
            return redirect(reverse('app:home'))

    return render(request, 'accaount/login.html', {'form': form})


def logout_view(request):
    logout(request)
    return redirect(reverse('account:login'))

app/views.py
from django.shortcuts import render

from django.views.generic import TemplateView

from app.filters import ResultFilter
from app.models import Category, Question, Result
from app.servieces import check_answer


class HomePageView(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        cd = super().get_context_data(**kwargs)
        cd['categories'] = Category.objects.all()
        return cd


def question_list(request , slug):
    category = Category.objects.get(slug=slug)
    questions = Question.objects.filter(category=category)


    if request.method == 'POST':
        context = check_answer(request , questions , category)
        return render(request , template_name='app/result.html' , context=context)

    context = {
        'questions':questions ,
        'category':category
    }
    return render(request , template_name='app/question_list.html' , context=context)

def result_list(request):
    filter = ResultFilter(request.GET , queryset=Result.objects.all())

    context = {
        'filter':filter
    }

    return render(request , template_name='app/result_list.html' , context=context)

templates/accaount/login.html
{% extends 'base.html' %}


{% block title %} Sign Up {% endblock %}


{% block content %}
    
    <form method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Login</button>
    </form>

{% endblock %}

templates/accaount/signup.html
{% extends 'base.html' %}


{% block title %} Sign Up {% endblock %}


{% block content %}
    
    <form method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit">SignUp</button>
    </form>

{% endblock %}

templates/app/question_list.html
{% extends 'base.html' %}

{% block title %} Question List {% endblock %}

{% block content %}
    <h3>Question List</h3>
    <hr>
    <form method="post">
    {% csrf_token %}
    {% for question in questions %}
        <p>{{ question.name }}</p>
        {% for answer in question.answers.all %}
            <label>{{ answer.name }}</label>
            <input type="radio" name="{{ question.name }}" value="{{ answer.id }}">
        {% endfor %}
    {% endfor %}
    <br>
    <br>
        <button type="submit"> Send </button>
    </form>
{% endblock %}

templates/app/result.html
{% extends 'base.html' %}
{% load float_format %}

{% block title %} Result {% endblock %}

{% block content %}

    <h1> Result Page</h1>
    <hr>
    <p> Category : {{ result.category }}</p>
    <p> Total question : {{ result.total_question }}</p>
    <p> Total correct : {{ result.total_correct }}</p>
    <p> Score : {{ result.score | float_format:3 }}</p>

{% endblock %}

templates/app/result_list.html
{% extends 'base.html' %}

{% block title %} Result list {% endblock %}

{% block content %}
    <h1> Result List Page</h1>

    <hr>
    <form method="get">
    {{ filter.form }}
    <button type="submit" >Search</button>

    </form>

    <form method="post">
    <table border="2">
        <thead>
        <tr>
            <td> ID </td>
            <td> User </td>
            <td> Total question </td>
            <td> correct </td>
            <td> Score </td>
            <td> Date </td>
            <td> Category </td>
        </tr>
        </thead>
        <tbody>
        {% for result in filter.qs %}
            <tr>
                <td> {{ result.id }}</td>
                <td> {{ result.user.phone }}</td>
                <td> {{ result.total_questions }}</td>
                <td> {{ result.total_correct }}</td>
                <td> {{ result.score }}</td>
                <td> {{ result.created_at | date:'Y-m-d' }}</td>
                <td> {{ result.category.name }}</td>
            </tr>
        {% endfor %}
        </tbody>


    </table>
    </form>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
<header>
    <a href="{% url 'app:home' %}"> Home </a> |
    {% if user.is_authenticated %}
        {{ user.phone }} ||
         <a href="{% url 'account:logout' %}" > Logout</a> |
        <a href="{% url 'app:result_list' %}"> Result list </a>
    {% else %}
        <a href="{% url 'account:login' %}"> Login </a>|
        <a href="{% url 'account:signup' %}"> Register </a>|
    {% endif %}
</header>
<hr>
<div>
    {% block content %}

    {% endblock %}
</div>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %} Home {% endblock %}

{% block content %}

    <h1> Home Page </h1>

    <hr>
  {% if user.is_authenticated %}
        {% for category in categories %}
        <a href="{% url 'app:question_list' category.slug %}"> {{ category.name }} </a>
        {% endfor %}
  {% endif %}

{% endblock %}